# Generated by Django 6.0.7 on 2026-07-28 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('summary', models.CharField(max_length=300, verbose_name='resumen')),
                ('description', models.TextField(verbose_name='descripción')),
                ('level', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='basico', max_length=20, verbose_name='nivel')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='miniatura')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('is_published', models.BooleanField(default=True, verbose_name='publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['track__order', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('icon', models.CharField(blank=True, help_text='Nombre del ícono SVG en static/images/icons/', max_length=50, verbose_name='ícono')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'eje temático',
                'verbose_name_plural': 'ejes temáticos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='curso')),
            ],
            options={
                'verbose_name': 'módulo',
                'verbose_name_plural': 'módulos',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.track', verbose_name='eje temático'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('vimeo_id', models.CharField(blank=True, help_text='Ej: 123456789 (de un video privado/con dominio restringido en Vimeo)', max_length=50, verbose_name='ID de video en Vimeo')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='duración (min)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('is_free_preview', models.BooleanField(default=False, help_text='Visible sin suscripción', verbose_name='vista previa gratuita')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='módulo')),
            ],
            options={
                'verbose_name': 'lección',
                'verbose_name_plural': 'lecciones',
                'ordering': ['order', 'id'],
                'unique_together': {('module', 'slug')},
            },
        ),
    ]
