# Generated by Django 6.0.7 on 2026-07-28 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', 'Mensual'), ('annual', 'Anual')], default='monthly', max_length=20, verbose_name='plan')),
                ('status', models.CharField(choices=[('incomplete', 'Incompleta'), ('trialing', 'En prueba'), ('active', 'Activa'), ('past_due', 'Pago pendiente'), ('canceled', 'Cancelada'), ('unpaid', 'Impaga')], default='incomplete', max_length=20, verbose_name='estado')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, verbose_name='ID cliente Stripe')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, verbose_name='ID suscripción Stripe')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='fin del período actual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'suscripción',
                'verbose_name_plural': 'suscripciones',
            },
        ),
    ]
